version: "3.8"
services:
  terraria:
    build: .
    container_name: terraria-server
    ports:
      - "7777:7777"
    volumes:
      - ./worlds:/root/.local/share/Terraria/Worlds
      - ./config:/config
    stdin_open: true
    tty: true
    restart: unless-stopped
